### ISSUE TITLE
Recurring events?

### ISSUE THREAD

**Issue by Egmund** [backdrop-contrib/fullcalendar#10]
Is there any way to have / create recurring events in fullcalendag?
Alternatively; is there an easy way to duplicate events?
I am used to the Drupal 7 calendar, wherein I could have recurring events.

**Comment by indigoxela** [comment]
> Is there any way to have / create recurring events in fullcalendag?

@Egmund the Fullcalendar module does not create anything, it's just a module to _display_ existing Dates.

> I am used to the Drupal 7 calendar, wherein I could have recurring events.

Neither does the Drupal Calendar module create any events - it's the Date module, that provides the fields. And the fields are attached to nodes.

You _possibly_ search for https://backdropcms.org/project/repeating_dates.

**Comment by Egmund** [comment]
Thank you for the quick response.
I did just install the 'repeating date' module, but am struggling with getting a repeated date show in the calendar (view). Any hints?

**Comment by indigoxela** [comment]
> I did just install the 'repeating date' module, but am struggling with getting a repeated date show in the calendar (view). Any hints?

Possibly because it's not a core Date field type, but a custom one? Never tried a combination of repeating_dates and fullcalendar. Maybe the maintainer can help here, pinging @laryn

**Comment by laryn** [comment]
The module will likely need to be adapted to work with the new repeating date type. I support that in theory but am not sure when I can look into adding it to this module -- a PR would be accepted if someone wants to give a shot!

**Comment by indigoxela** [comment]
> The module will likely need to be adapted to work with the new repeating date type. I support that in theory but am not sure when I can look into adding it to this module

I took a look recently, but it's probably easier to start fresh. Support for additional date fields as well as updating the library (currently legacy 1.5) would be *a lot* of work. Fullcalendar (module) with all its settings and submodules and whistles and bells is daunting.

**Comment by indigoxela** [comment]
@Egmund if you're adventurous .... I started working on a new module that is way simpler, but supports more date (field) types: [Fullcalendar Views NG](https://github.com/backdrop-contrib/fullcalendar_views) (Caution, Friday afternoon code :wink: Don't test on production sites.)

@laryn If you're interested in enhancing Fullcalendar legacy module, have a look at how the other one [handles different date types](https://github.com/backdrop-contrib/fullcalendar_views/blob/93f797285fb6a27601e82ad39ff0031099a8ffdf/views/fullcalendar_views_style_calendar.inc#L219).

**Comment by Egmund** [comment]
I would be very interested in testing, but do not know how to install from github.

**Comment by indigoxela** [comment]
> I would be very interested in testing, but do not know how to install from github.

It's not tricky, GitHub also provides zip files, I updated the [readme](https://github.com/backdrop-contrib/fullcalendar_views#install-from-github) with instructions. If you're running into trouble open an issue in the fullcalendar_views queue.

**Comment by Egmund** [comment]
Thank you. I did not se the zip file before.
Installed & I will play around.

**Comment by Egmund** [comment]
I am getting somewhere:
Got the proper title - but it is not clickable, so content not showing.
Got it to repeat. Two things needed to be changed. The field need to be set to 'unlimited' in content type. The date field in view need to have un-checked 'show all values on same line'

**Comment by indigoxela** [comment]
I think, this issue could get closed. A new module is now available, that is able to display events from repeating_dates (fullcalendar_views).

**Comment by Egmund** [comment]
Indeed.
& thank you for all this work. Now BackdropCMS is, for me, as useful as Drupal 7
