### ISSUE TITLE
Module hook conflict breaks sites

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/fullcalendar#11]
Long story short:

- Module fullcalendar implements hook_views_query_alter()
- Now a module fullcalendar_views exists
- So this hook gets interpreted as hook_query_alter()
- Breaking sites with `Error: Call to a member function get_option() on null in fullcalendar_views_query_alter`

Two options:

1) Module fullcalendar does a check, if this is actually the right hook, or an isset() on the required propery, or the base class...

2) Module fullcalendar_views gets renamed to fullcalendarviews, so the hook isn't ambiguous anymore (module has a release, unfortunately)

@laryn what do you think?

https://github.com/backdrop-contrib/fullcalendar_views/issues/7

Solution in hook_views_query_alter in this module:
```
  if (!isset($query)) {
    return;
  }
```

**Comment by laryn** [comment]
Seems reasonable -- thanks!
