### ISSUE TITLE
"Link to original content" not working

### ISSUE THREAD

**Issue by OpsTao** [backdrop-contrib/fullcalendar#8]
Trying to set up FullCalendar and associated custom content type to work in Backdrop as it had been working in Drupal 7. A content type "Calendar Event" was created, and the View settings for FullCalendar are reading on those fields. However the Title field option "Link this field to the original piece of content" isn't working as expected. It loads the page containing a FullCalendar block into a new tab, and reports "link not found." What am I missing?

**Comment by laryn** [comment]
Can you attach an export of your view as a text file here?

**Comment by OpsTao** [comment]
A text file export of a view is new to me, but I think I found it correctly; attached. 
[calendar_view-export.txt](https://github.com/backdrop-contrib/fullcalendar/files/3597427/calendar_view-export.txt)

**Comment by laryn** [comment]
@OpsTao If I'm reading this export correctly, my first suggestion is to uncheck this box in FullCalendar settings on the View:

![Screen Shot 2019-09-10 at 3 52 47 PM](https://user-images.githubusercontent.com/871421/64649735-1d0dee80-d3e3-11e9-9b36-a97ed00f56b5.jpg)

**Comment by OpsTao** [comment]
**You are correct, that solves the problem. Thanks!** 
However opens the original content in a separate tab – not necessarily bad but I don't see what is making it do that. 

**What I really would prefer:** Can you imagine a way to get a FullCalendar content item to open in a lightbox-type modal window (maybe via ColorBox module), and showing only the core text content, not enclosed in a site default page?

**Comment by laryn** [comment]
@OpsTao That might be possible with [Colorbox Node](https://www.drupal.org/project/colorbox_node), but I don't think it's ported (yet). If you are able to port and test it that would be great, otherwise you can [put in a port request here](https://github.com/backdrop-ops/contrib/issues).

See [this example question/answer](https://drupal.stackexchange.com/questions/111733/link-field-to-node-content-only-with-colorbox).
